# @todo: Upload assets to this GitHub release.

name: Publish on PyPI
on:
  workflow_dispatch:
  release:
    types:
      - released
jobs:
  publish:
    name: Publish on PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          cache: pip
          run: pip install poetry
      - name: Build and publish
        env:
          # @todo: Set and use POETRY_PYPI_TOKEN_PYPI env variable for PyPi token authentication.
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          poetry build -f wheel
          poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD
