name: Publish on PyPI
on:
  workflow_dispatch:
  release:
    types:
      - released
jobs:
  publish:
    name: Publish on PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Build and publish
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip install poetry
        poetry build -f wheel
        poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD
      # @todo: Add artifacts from /dist to this GitHub release.
